### ISSUE TITLE
Mulit-line comment

### ISSUE THREAD

**Issue by bcoady** [onerobotics/vim-tp#1]
Inserted the following after line 144 in the syntax file:

```
syn match       tpComment           /\(\s*\d*:\s*\)\@<=--eg:.*/
```

Multi-line comments are now highlited just like single line comments.

**Comment by bcoady** [comment]
Closing the issue. I am working on a fork to complete some of the missing syntax items e.g. vision and offset commands,  as well as add spell checking support for comments.

**Comment by unreal** [comment]
Great -- looking forward to the pull request. I think I took a stab at this comment-style a while back, but I couldn't get it to match subsequent lines correctly.
