### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by bcoady** [onerobotics/vim-tp#2]
Jay,

  I have been using your syntax highlighter for about a week and it has completely revolutionized my world. I created a Snipmate snippets file here https://github.com/bcoady/vim-tp-snippets.git of my most commonly used commands. Let me know what you think. 

Cheers,
Ben Coady

**Comment by unreal** [comment]
Hey Ben, not sure why I never responded to this... sorry! Just wanted to say thanks for creating the snippets file. I need to get in the habit of using them!
